#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "site"
BASE_URL = "https://between-potential-and-ideal.onrender.com"
LANGUAGES = ("tlh", "qya")
FORMATS = ("html", "pdf", "docx", "md", "txt")
PACKAGES = (
    "between-potential-and-ideal",
    "between-potential-and-ideal-editorial",
    "between-potential-and-ideal-tightened",
    "editorial-report",
    "stories-before-thought",
    "the-nauseating-truth",
    "what-ai-believes",
    "when-i-am-also-you",
    "reverse-turing-conversation",
)
PAGE_SLUGS = (
    "about", "ai-as-witness", "ai-believes", "ai-open-problems", "ai", "applied",
    "art-of-potential", "black-holes-horizons-holography", "boundary-horizons", "changelog",
    "core", "critique", "discussion", "education-of-potential", "files", "glossary",
    "high-energy-physics", "i-have-no-mouth", "law-of-potential",
    "locality-nonlocality-contextuality", "medicine-of-potential", "methodology",
    "mistake-repeats", "music-of-potential", "potential-extensions",
    "potential-ideal-optimal", "recursive-edge", "response",
    "science-physics-math-boundary-discipline", "shape-of-the-universe-and-potential",
    "sources", "stories", "summary", "witness",
)
SEGMENTS = {
    "summary": [20, 30, 40],
    "core": [100, 110],
    "methodology": [40, 50, 60],
    "witness": [170, 180],
    "ai-as-witness": [170],
    "ai-open-problems": [180],
    "ai": [170, 180, 190],
    "applied": [390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510],
    "art-of-potential": [370],
    "black-holes-horizons-holography": [660],
    "boundary-horizons": [550],
    "critique": [40, 50, 60],
    "education-of-potential": [120],
    "high-energy-physics": [630, 640, 650],
    "i-have-no-mouth": [190],
    "law-of-potential": [480, 490, 500],
    "locality-nonlocality-contextuality": [310, 320, 330],
    "medicine-of-potential": [510],
    "music-of-potential": [380],
    "potential-extensions": [520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620],
    "recursive-edge": [250],
    "science-physics-math-boundary-discipline": [300],
    "shape-of-the-universe-and-potential": [600, 610, 620],
    "sources": [750, 760, 770, 780],
}
TIGHTENED_SEGMENTS = (
    20, 30, 40, 50, 60, 70, 100, 110, 120, 160, 170, 180, 250, 300,
    340, 370, 380, 390, 420, 450, 480, 510, 550, 600, 630, 660, 750, 760,
    770, 780,
)

LABELS = {
    "tlh": {
        "language": "tlhIngan Hol",
        "home": "juH",
        "summary": "qIjmeH ghItlh ngaj",
        "glossary": "mu'ghom",
        "concepts": "Potential, Ideal, Optimal",
        "ai-as-witness": "AI leghwI'",
        "methodology": "mIw",
        "core": "botlh",
        "witness": "leghwI'",
        "applied": "lo'mey",
        "ai": "AI",
        "files": "ghItlhmey",
        "critique": "poj",
        "sources": "mungmey",
        "about": "jInmol bopbogh De'",
        "changelog": "choHmey",
        "skip": "Doch potlhDaq yIjaH",
        "hero_title": "DuH chenchoHmeH poH bopbogh QubmeH nID.",
        "hero_lead": "naDev qo' jangghach SoQ 'oHbe'. Potentialvo', leghwI'ghach, wIv, Qu' je veghbogh vIHghach 'oH.",
        "hero_note": "laDmeH He: botlh, leghwI', lo'mey je. QeD, bom, lut je pImtaH; vaj qech SoQ tu'lu'be'.",
        "start": "naDev yItagh",
        "start_text": "QubmeH ghItlh, pat QeD, lutmey, lo'mey je tay'moH jInmolvam. qIjmeH ghItlh ngaj yIlaD, ghIq ghItlh poQHa' yIlaD, tagha' ghItlh naQ je rarghachmey yIpoSmoH.",
        "read_summary": "qIjmeH ghItlh ngaj yIlaD",
        "continue_core": "botlhDaq yIjaH",
        "full_document": "ghItlh naQ",
        "tightened": "ghItlh poQHa'",
        "download": "yItlhap",
        "open": "yIpoSmoH",
        "experimental_note": "tlhIngan Hol ghItlhvam mIw jan boQmo' chen. qechmey, rarghachmey, pongmey je polmeH QA lulo'lu'; Holtej naQ 'olbe'lu'pu'.",
        "footer": "laDmeH, pojmeH, Qubqa'meH je poSbogh QubmeH nID.",
    },
    "qya": {
        "language": "Neo-Quenya",
        "home": "Yesta",
        "summary": "Sinta Quenta",
        "glossary": "Quettaparma",
        "concepts": "Potential, Ideal, Optimal",
        "ai-as-witness": "AI Astarmo",
        "methodology": "Lé Cestalië",
        "core": "Endë",
        "witness": "Astarmë",
        "applied": "Antacarmar",
        "ai": "AI",
        "files": "Parmar",
        "critique": "Cesta",
        "sources": "Celur",
        "about": "I Cesta",
        "changelog": "Vista Ahyalië",
        "skip": "Á lelya i alta nassë",
        "hero_title": "Sanwë-cesta i lúmessë yassë námië yesta harya canta.",
        "hero_lead": "Sí cuilë lá ná quanta hanquenta, mal menë: námiello ter astarmë, cilmë ar mauya-cárië ana canta valda amba.",
        "hero_note": "I nómë anta tië cendaliëo: endë, astarmë ar antacarmar. Nólë, lírë ar nyári lemya sundo pelli, an i sanwë polë ná cendaina ú carna tancavë.",
        "start": "Á yesta sí",
        "start_text": "Sin ná sanwë-cesta yassë quenta nolmava, lé silmava, nyári ar antacarmar nar hostainë. Á yesta sinta quentanen, lelya i quenta hostaina, ar apa sa á panta i quanta parma ar i yáni.",
        "read_summary": "Á cenda i sinta quenta",
        "continue_core": "Á lelya i endenna",
        "full_document": "Quanta parma",
        "tightened": "Quenta hostaina",
        "download": "Á mapa",
        "open": "Á panta",
        "experimental_note": "Sin Neo-Quenya quenta ná carna mahtalë-yanen. Sanwi, yávi, yáni ar essi nar cennë lé-yanen; lá ná quanta tengwesta-cesta lorello.",
        "footer": "Sanwë-cesta pantaina cendalië, cestalië ar enta-carien.",
    },
}
NAV_KEYS = (
    ("home", None),
    ("summary", "summary"),
    ("glossary", "glossary"),
    ("concepts", "potential-ideal-optimal"),
    ("ai-as-witness", "ai-as-witness"),
    ("methodology", "methodology"),
    ("core", "core"),
    ("witness", "witness"),
    ("applied", "applied"),
    ("ai", "ai"),
    ("files", "files"),
    ("critique", "critique"),
    ("sources", "sources"),
)
